application: secretaria-jdf
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /app/.*
  script: main.app

- url: /(.*)/
  static_files: /www/\1/index.html
  upload: www/.*/index.html

- url: (.*)
  static_files: www/\1
  upload: www/.*


libraries:
- name: webapp2
  version: "2.5.2"

